name: benchmarks

on:
  push:
    branches:
      - master

env:
  GRADLE_OPTS: -Dorg.gradle.console=plain

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 14-ea]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-v1-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v1-
      # TODO KONAN_DATA_DIR might allow us a combined cache in the future.
      - name: Konan Cache
        uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-v1-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-konan-v1-
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Benchmark ${{ matrix.java }}
        run: ./gradlew jmh --stacktrace
