name: benchmarks

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

env:
  GRADLE_OPTS: -Dorg.gradle.console=plain -Xmx2048m -Xms1024m

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 13]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Benchmark ${{ matrix.java }}
        run: ./gradlew jmh --stacktrace
