name: Gradle Wrapper Validation

on:
  pull_request:
    paths:
      - 'gradle/wrapper/*'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
