name: JVM Test

on:
  pull_request:
    paths-ignore:
      - '*.md'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  KONAN_DATA_DIR: ~/.gradle/konan

jobs:
  job:
    name: JVM Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [6, 8, 12, 14-ea]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jre
      - run: which -a java
      - name: Test
        run: ./gradlew jvmTest --stacktrace
