name: Native Test

on:
  pull_request:
    paths-ignore:
      - '*.md'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  KONAN_DATA_DIR: ~/.gradle/konan

jobs:
  job:
    name: Native Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test
        if: ${{ matrix.os }} == 'macOS-latest'
        run: ./gradlew macosX64Test --stacktrace
      - name: Test
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: ./gradlew linuxX64Test --stacktrace
      - name: Test
        if: ${{ matrix.os }} == 'windows-latest'
        run: ./gradlew.bat mingwX64 --stacktrace
