name: pr

on:
  pull_request:
    paths-ignore:
      - '*.md'

env:
  GRADLE_OPTS: -Dorg.gradle.console=plain -Xmx2048m -Xms1024m

jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew macosX64Test --stacktrace
  ios:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew iosTest --stacktrace
  tvos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew tvosTest --stacktrace
  watchos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew watchosTest --stacktrace
  mingw:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew mingwX64Test --stacktrace
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew linuxX64Test --stacktrace
  js-browser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew jsBrowserTest --stacktrace
  js-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew jsNodeTest --stacktrace
  jvm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [6, 8, 11, 13, 14-ea]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: ./gradlew jvmTest --stacktrace
