name: PR

on:
  pull_request:
    paths-ignore:
      - '*.md'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  KONAN_DATA_DIR: ~/.gradle/konan

jobs:
  native:
    name: Native Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test
        run: ./gradlew nativeTest --stacktrace
  js:
    name: JS Test
    runs-on: ubuntu-latest
    jobs:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test
        run: ./gradlew jsTest --stacktrace
  jvm:
    name: JVM Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [6, 8, 11, 14-ea]
    jobs:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test
        run: JAVA_HOME=/usr/bin/java ./gradlew jvmTest --stacktrace -Dorg.gradle.java.home="$(command -v java)"
