name: PR

on:
  pull_request:
    paths-ignore:
      - '*.md'

env:
  KONAN_DATA_DIR: ~/.gradle/konan

jobs:
  Native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # We test with the oldest JDK, all LTS, the latest, and the current EA.
      #
      # https://github.com/actions/setup-java/issues/44
      - name: Setup Java 6
        uses: actions/setup-java@v1
        with:
          java-version: 6
      - name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Java 14-ea
        uses: actions/setup-java@v1
        with:
          java-version: 14-ea
      - name: Setup Java 13
        uses: actions/setup-java@v1
        with:
          java-version: 13

#      - name: Native Test
#        run: ./gradlew nativeTest --stacktrace
#      - name: JavaScript Test
#        run: ./gradlew jsTest --stacktrace
      - name: Java Test
        # language=sh
        run: |
          printenv | grep 'JAVA_HOME_'

      # We need to stop the Gradle Daemon because otherwise we end up with stuff
      # in the cache we do not want and it plainly fails on Windows.
      - name: Stop Gradle Daemon
        run: ./gradlew --stop
