name: PR

on:
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('.kotlin-version', '**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Konan Cache
        uses: actions/cache@v1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('.kotlin-version') }}
          restore-keys: |
            ${{ runner.os }}-konan-
      - name: ${{ matrix.os }}
        run: ./gradlew check --stacktrace
