name: PR

on:
  pull_request:
    paths-ignore:
      - '*.md'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  KONAN_DATA_DIR: ~/.gradle/konan

jobs:
  Native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle JVM
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Test
        run: ./gradlew nativeTest --stacktrace
  JavaScript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle JVM
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Test
        run: ./gradlew jsTest --stacktrace
  Java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [6, 8, 11, 13, 14-ea]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle JVM
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Prepare Gradle JVM
        run: echo "$JAVA_HOME" >.gradle-jvm

      - name: Setup Kotlin JVM
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Prepare Kotlin JVM
        run: echo "$JAVA_HOME" >.kotlin-jvm

      - name: Test
        run: JAVA_HOME="$(cat .gradle-jvm)" KOTLIN_JAVA_HOME="$(cat .kotlin-jvm)" ./gradlew jvmTest --stacktrace
