name: PR

on:
  pull_request:
    paths-ignore:
      - '*.md'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  KONAN_DATA_DIR: ~/.gradle/konan

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [6, 8, 11, 14-ea]
        os: [macOS-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*gradle.*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test
        if: matrix.java == 11 && matrix.os == 'macOS-latest'
        run: ./gradlew macosX64Test --stacktrace
      - name: Test
        if: matrix.java == 11 matrix.os == 'windows-latest'
        run: ./gradlew.bat mingwX64 --stacktrace
      - name: Test
        if: matrix.java == 11 && matrix.os == 'ubuntu-latest'
        run: ./gradlew jsTest jvmTest linuxX64Test --stacktrace
      - name: JVM Test
        if: matrix.java != 11 && matrix.os == 'ubuntu-latest'
        run: which -a java && ./gradlew jvmTest --stacktrace
